import type { Instructor } from '@/types/instructor';

export const mockInstructors: Instructor[] = [
  {
    id: '1',
    name: 'Nguyễn Văn A',
    title: 'Giảng viên cao cấp',
    bio: 'Chuyên gia về lập trình web với hơn 10 năm kinh nghiệm. Tác giả của nhiều khóa học về React, Node.js và TypeScript.',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=NguyenVanA',
    specialties: ['React', 'Node.js', 'TypeScript', 'Full Stack'],
    rating: 4.8,
    totalStudents: 15230,
    totalCourses: 12,
    experience: 10,
    socialLinks: {
      linkedin: 'https://linkedin.com/in/nguyen-van-a',
      youtube: 'https://youtube.com/@nguyen-van-a',
    },
  },
  {
    id: '2',
    name: 'Trần Thị B',
    title: 'Chuyên gia UI/UX',
    bio: 'Nhà thiết kế giao diện người dùng với niềm đam mê tạo ra những trải nghiệm tuyệt vời. Tốt nghiệp Đại học Bách khoa.',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=TranThiB',
    specialties: ['UI/UX Design', 'Figma', 'Design System', 'Prototyping'],
    rating: 4.9,
    totalStudents: 23450,
    totalCourses: 18,
    experience: 8,
    socialLinks: {
      behance: 'https://behance.net/tran-thi-b',
      linkedin: 'https://linkedin.com/in/tran-thi-b',
    },
  },
  {
    id: '3',
    name: 'Lê Minh C',
    title: 'Giảng viên Python',
    bio: 'Chuyên gia về Python và Machine Learning. Có nhiều năm làm việc tại các công ty công nghệ hàng đầu.',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LeMinhC',
    specialties: ['Python', 'Machine Learning', 'Data Science', 'AI'],
    rating: 4.7,
    totalStudents: 18900,
    totalCourses: 15,
    experience: 12,
    socialLinks: {
      github: 'https://github.com/le-minh-c',
      linkedin: 'https://linkedin.com/in/le-minh-c',
    },
  },
  {
    id: '4',
    name: 'Phạm Thị D',
    title: 'Chuyên gia Marketing',
    bio: 'Chuyên gia marketing số với hơn 7 năm kinh nghiệm. Từng làm việc tại các agency quảng cáo lớn.',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=PhamThiD',
    specialties: ['Digital Marketing', 'SEO', 'Content Marketing', 'Social Media'],
    rating: 4.6,
    totalStudents: 11200,
    totalCourses: 10,
    experience: 7,
    socialLinks: {
      facebook: 'https://facebook.com/pham-thi-d',
      linkedin: 'https://linkedin.com/in/pham-thi-d',
    },
  },
  {
    id: '5',
    name: 'Hoàng Văn E',
    title: 'Giảng viên Mobile',
    bio: 'Chuyên gia phát triển ứng dụng mobile với React Native và Flutter. Tác giả của nhiều ứng dụng nổi tiếng.',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=HoangVanE',
    specialties: ['React Native', 'Flutter', 'iOS', 'Android'],
    rating: 4.8,
    totalStudents: 16780,
    totalCourses: 14,
    experience: 9,
    socialLinks: {
      github: 'https://github.com/hoang-van-e',
      youtube: 'https://youtube.com/@hoang-van-e',
    },
  },
  {
    id: '6',
    name: 'Vũ Thị F',
    title: 'Chuyên gia Data',
    bio: 'Chuyên gia phân tích dữ liệu và Business Intelligence. Có nhiều năm kinh nghiệm trong lĩnh vực tài chính và ngân hàng.',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=VuThiF',
    specialties: ['Data Analysis', 'SQL', 'Power BI', 'Excel'],
    rating: 4.7,
    totalStudents: 9800,
    totalCourses: 9,
    experience: 6,
    socialLinks: {
      linkedin: 'https://linkedin.com/in/vu-thi-f',
    },
  },
  {
    id: '7',
    name: 'Đỗ Văn G',
    title: 'Giảng viên DevOps',
    bio: 'Chuyên gia về DevOps và Cloud Computing. Có chứng chỉ AWS và Azure. Từng làm việc tại các công ty công nghệ lớn.',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=DoVanG',
    specialties: ['DevOps', 'AWS', 'Docker', 'Kubernetes', 'CI/CD'],
    rating: 4.9,
    totalStudents: 14560,
    totalCourses: 11,
    experience: 11,
    socialLinks: {
      github: 'https://github.com/do-van-g',
      linkedin: 'https://linkedin.com/in/do-van-g',
    },
  },
  {
    id: '8',
    name: 'Bùi Thị H',
    title: 'Chuyên gia tiếng Anh',
    bio: 'Giảng viên tiếng Anh với chứng chỉ TESOL. Có nhiều năm kinh nghiệm giảng dạy cho học sinh và sinh viên.',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=BuiThiH',
    specialties: ['English', 'IELTS', 'TOEFL', 'Business English'],
    rating: 4.8,
    totalStudents: 20340,
    totalCourses: 16,
    experience: 8,
    socialLinks: {
      linkedin: 'https://linkedin.com/in/bui-thi-h',
    },
  },
];
